#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="abb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReading(Reading instance);
    partial void UpdateReading(Reading instance);
    partial void DeleteReading(Reading instance);
    partial void InsertTotal_Reading(Total_Reading instance);
    partial void UpdateTotal_Reading(Total_Reading instance);
    partial void DeleteTotal_Reading(Total_Reading instance);
    partial void InsertTReading(TReading instance);
    partial void UpdateTReading(TReading instance);
    partial void DeleteTReading(TReading instance);
    partial void InsertTTotal_Reading(TTotal_Reading instance);
    partial void UpdateTTotal_Reading(TTotal_Reading instance);
    partial void DeleteTTotal_Reading(TTotal_Reading instance);
    partial void InsertFile(File instance);
    partial void UpdateFile(File instance);
    partial void DeleteFile(File instance);
    partial void InsertSiteStatus(SiteStatus instance);
    partial void UpdateSiteStatus(SiteStatus instance);
    partial void DeleteSiteStatus(SiteStatus instance);
    partial void InsertSiteRegion(SiteRegion instance);
    partial void UpdateSiteRegion(SiteRegion instance);
    partial void DeleteSiteRegion(SiteRegion instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::db.Properties.Settings.Default.abbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Reading> Readings
		{
			get
			{
				return this.GetTable<Reading>();
			}
		}
		
		public System.Data.Linq.Table<Total_Reading> Total_Readings
		{
			get
			{
				return this.GetTable<Total_Reading>();
			}
		}
		
		public System.Data.Linq.Table<TReading> TReadings
		{
			get
			{
				return this.GetTable<TReading>();
			}
		}
		
		public System.Data.Linq.Table<TTotal_Reading> TTotal_Readings
		{
			get
			{
				return this.GetTable<TTotal_Reading>();
			}
		}
		
		public System.Data.Linq.Table<File> Files
		{
			get
			{
				return this.GetTable<File>();
			}
		}
		
		public System.Data.Linq.Table<v_Total_Readings_60day> v_Total_Readings_60days
		{
			get
			{
				return this.GetTable<v_Total_Readings_60day>();
			}
		}
		
		public System.Data.Linq.Table<SiteStatus> SiteStatus
		{
			get
			{
				return this.GetTable<SiteStatus>();
			}
		}
		
		public System.Data.Linq.Table<SiteRegion> SiteRegions
		{
			get
			{
				return this.GetTable<SiteRegion>();
			}
		}
		
		public System.Data.Linq.Table<Status> Status
		{
			get
			{
				return this.GetTable<Status>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Copy_Session_Records")]
		public int sp_Copy_Session_Records([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> session)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), session);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Copy_TTotal_Readings")]
		public int sp_Copy_TTotal_Readings([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string slot_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReturnMessage", DbType="VarChar(100)")] ref string returnMessage)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slot_id, returnMessage);
			returnMessage = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Remove_slot_id_records")]
		public int sp_Remove_slot_id_records([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string slot_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slot_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Insert_TTotal_Reading")]
		public int sp_Insert_TTotal_Reading([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> slot_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SiteName", DbType="NChar(10)")] string siteName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChName", DbType="NChar(10)")] string chName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dtime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> reading, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string reading_units, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> flow, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string flow_units, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> file_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> row)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slot_id, id, siteName, chName, dtime, reading, reading_units, flow, flow_units, file_id, row);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Remove_Empty_TTotal_Readings")]
		public int sp_Remove_Empty_TTotal_Readings()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AFUse")]
		public int sp_AFUse([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site", DbType="VarChar(10)")] string site, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> days)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), site, days);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Readings")]
	public partial class Reading : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _SiteName;
		
		private string _ChName;
		
		private System.Nullable<System.DateTime> _dtime;
		
		private System.Nullable<double> _reading1;
		
		private System.Nullable<System.Guid> _file_id;
		
		private System.Nullable<int> _row;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnChNameChanging(string value);
    partial void OnChNameChanged();
    partial void OndtimeChanging(System.Nullable<System.DateTime> value);
    partial void OndtimeChanged();
    partial void Onreading1Changing(System.Nullable<double> value);
    partial void Onreading1Changed();
    partial void Onfile_idChanging(System.Nullable<System.Guid> value);
    partial void Onfile_idChanged();
    partial void OnrowChanging(System.Nullable<int> value);
    partial void OnrowChanged();
    #endregion
		
		public Reading()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChName", DbType="VarChar(10)")]
		public string ChName
		{
			get
			{
				return this._ChName;
			}
			set
			{
				if ((this._ChName != value))
				{
					this.OnChNameChanging(value);
					this.SendPropertyChanging();
					this._ChName = value;
					this.SendPropertyChanged("ChName");
					this.OnChNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtime
		{
			get
			{
				return this._dtime;
			}
			set
			{
				if ((this._dtime != value))
				{
					this.OndtimeChanging(value);
					this.SendPropertyChanging();
					this._dtime = value;
					this.SendPropertyChanged("dtime");
					this.OndtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="reading", Storage="_reading1", DbType="Float")]
		public System.Nullable<double> reading1
		{
			get
			{
				return this._reading1;
			}
			set
			{
				if ((this._reading1 != value))
				{
					this.Onreading1Changing(value);
					this.SendPropertyChanging();
					this._reading1 = value;
					this.SendPropertyChanged("reading1");
					this.Onreading1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> file_id
		{
			get
			{
				return this._file_id;
			}
			set
			{
				if ((this._file_id != value))
				{
					this.Onfile_idChanging(value);
					this.SendPropertyChanging();
					this._file_id = value;
					this.SendPropertyChanged("file_id");
					this.Onfile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_row", DbType="Int")]
		public System.Nullable<int> row
		{
			get
			{
				return this._row;
			}
			set
			{
				if ((this._row != value))
				{
					this.OnrowChanging(value);
					this.SendPropertyChanging();
					this._row = value;
					this.SendPropertyChanged("row");
					this.OnrowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Total_Readings")]
	public partial class Total_Reading : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _SiteName;
		
		private string _ChName;
		
		private System.Nullable<System.DateTime> _dtime;
		
		private System.Nullable<double> _reading;
		
		private string _reading_units;
		
		private System.Nullable<double> _flow;
		
		private string _flow_units;
		
		private System.Nullable<System.Guid> _file_id;
		
		private System.Nullable<int> _row;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnChNameChanging(string value);
    partial void OnChNameChanged();
    partial void OndtimeChanging(System.Nullable<System.DateTime> value);
    partial void OndtimeChanged();
    partial void OnreadingChanging(System.Nullable<double> value);
    partial void OnreadingChanged();
    partial void Onreading_unitsChanging(string value);
    partial void Onreading_unitsChanged();
    partial void OnflowChanging(System.Nullable<double> value);
    partial void OnflowChanged();
    partial void Onflow_unitsChanging(string value);
    partial void Onflow_unitsChanged();
    partial void Onfile_idChanging(System.Nullable<System.Guid> value);
    partial void Onfile_idChanged();
    partial void OnrowChanging(System.Nullable<int> value);
    partial void OnrowChanged();
    #endregion
		
		public Total_Reading()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChName", DbType="NChar(10)")]
		public string ChName
		{
			get
			{
				return this._ChName;
			}
			set
			{
				if ((this._ChName != value))
				{
					this.OnChNameChanging(value);
					this.SendPropertyChanging();
					this._ChName = value;
					this.SendPropertyChanged("ChName");
					this.OnChNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtime
		{
			get
			{
				return this._dtime;
			}
			set
			{
				if ((this._dtime != value))
				{
					this.OndtimeChanging(value);
					this.SendPropertyChanging();
					this._dtime = value;
					this.SendPropertyChanged("dtime");
					this.OndtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading", DbType="Float")]
		public System.Nullable<double> reading
		{
			get
			{
				return this._reading;
			}
			set
			{
				if ((this._reading != value))
				{
					this.OnreadingChanging(value);
					this.SendPropertyChanging();
					this._reading = value;
					this.SendPropertyChanged("reading");
					this.OnreadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading_units", DbType="NChar(10)")]
		public string reading_units
		{
			get
			{
				return this._reading_units;
			}
			set
			{
				if ((this._reading_units != value))
				{
					this.Onreading_unitsChanging(value);
					this.SendPropertyChanging();
					this._reading_units = value;
					this.SendPropertyChanged("reading_units");
					this.Onreading_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow", DbType="Float")]
		public System.Nullable<double> flow
		{
			get
			{
				return this._flow;
			}
			set
			{
				if ((this._flow != value))
				{
					this.OnflowChanging(value);
					this.SendPropertyChanging();
					this._flow = value;
					this.SendPropertyChanged("flow");
					this.OnflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_units", DbType="NChar(10)")]
		public string flow_units
		{
			get
			{
				return this._flow_units;
			}
			set
			{
				if ((this._flow_units != value))
				{
					this.Onflow_unitsChanging(value);
					this.SendPropertyChanging();
					this._flow_units = value;
					this.SendPropertyChanged("flow_units");
					this.Onflow_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> file_id
		{
			get
			{
				return this._file_id;
			}
			set
			{
				if ((this._file_id != value))
				{
					this.Onfile_idChanging(value);
					this.SendPropertyChanging();
					this._file_id = value;
					this.SendPropertyChanged("file_id");
					this.Onfile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_row", DbType="Int")]
		public System.Nullable<int> row
		{
			get
			{
				return this._row;
			}
			set
			{
				if ((this._row != value))
				{
					this.OnrowChanging(value);
					this.SendPropertyChanging();
					this._row = value;
					this.SendPropertyChanged("row");
					this.OnrowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TReadings")]
	public partial class TReading : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _SiteName;
		
		private string _ChName;
		
		private System.Nullable<System.DateTime> _dtime;
		
		private System.Nullable<double> _reading;
		
		private System.Nullable<System.Guid> _session;
		
		private System.Nullable<System.Guid> _file_id;
		
		private System.Nullable<int> _row;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnChNameChanging(string value);
    partial void OnChNameChanged();
    partial void OndtimeChanging(System.Nullable<System.DateTime> value);
    partial void OndtimeChanged();
    partial void OnreadingChanging(System.Nullable<double> value);
    partial void OnreadingChanged();
    partial void OnsessionChanging(System.Nullable<System.Guid> value);
    partial void OnsessionChanged();
    partial void Onfile_idChanging(System.Nullable<System.Guid> value);
    partial void Onfile_idChanged();
    partial void OnrowChanging(System.Nullable<int> value);
    partial void OnrowChanged();
    #endregion
		
		public TReading()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="VarChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChName", DbType="VarChar(10)")]
		public string ChName
		{
			get
			{
				return this._ChName;
			}
			set
			{
				if ((this._ChName != value))
				{
					this.OnChNameChanging(value);
					this.SendPropertyChanging();
					this._ChName = value;
					this.SendPropertyChanged("ChName");
					this.OnChNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtime
		{
			get
			{
				return this._dtime;
			}
			set
			{
				if ((this._dtime != value))
				{
					this.OndtimeChanging(value);
					this.SendPropertyChanging();
					this._dtime = value;
					this.SendPropertyChanged("dtime");
					this.OndtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading", DbType="Float")]
		public System.Nullable<double> reading
		{
			get
			{
				return this._reading;
			}
			set
			{
				if ((this._reading != value))
				{
					this.OnreadingChanging(value);
					this.SendPropertyChanging();
					this._reading = value;
					this.SendPropertyChanged("reading");
					this.OnreadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> session
		{
			get
			{
				return this._session;
			}
			set
			{
				if ((this._session != value))
				{
					this.OnsessionChanging(value);
					this.SendPropertyChanging();
					this._session = value;
					this.SendPropertyChanged("session");
					this.OnsessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> file_id
		{
			get
			{
				return this._file_id;
			}
			set
			{
				if ((this._file_id != value))
				{
					this.Onfile_idChanging(value);
					this.SendPropertyChanging();
					this._file_id = value;
					this.SendPropertyChanged("file_id");
					this.Onfile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_row", DbType="Int")]
		public System.Nullable<int> row
		{
			get
			{
				return this._row;
			}
			set
			{
				if ((this._row != value))
				{
					this.OnrowChanging(value);
					this.SendPropertyChanging();
					this._row = value;
					this.SendPropertyChanged("row");
					this.OnrowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTotal_Readings")]
	public partial class TTotal_Reading : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _slot_id;
		
		private System.Nullable<System.Guid> _id;
		
		private string _SiteName;
		
		private string _ChName;
		
		private System.Nullable<System.DateTime> _dtime;
		
		private System.Nullable<double> _reading;
		
		private string _reading_units;
		
		private System.Nullable<double> _flow;
		
		private string _flow_units;
		
		private System.Nullable<System.Guid> _file_id;
		
		private System.Nullable<int> _row;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onslot_idChanging(string value);
    partial void Onslot_idChanged();
    partial void OnidChanging(System.Nullable<System.Guid> value);
    partial void OnidChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnChNameChanging(string value);
    partial void OnChNameChanged();
    partial void OndtimeChanging(System.Nullable<System.DateTime> value);
    partial void OndtimeChanged();
    partial void OnreadingChanging(System.Nullable<double> value);
    partial void OnreadingChanged();
    partial void Onreading_unitsChanging(string value);
    partial void Onreading_unitsChanged();
    partial void OnflowChanging(System.Nullable<double> value);
    partial void OnflowChanged();
    partial void Onflow_unitsChanging(string value);
    partial void Onflow_unitsChanged();
    partial void Onfile_idChanging(System.Nullable<System.Guid> value);
    partial void Onfile_idChanged();
    partial void OnrowChanging(System.Nullable<int> value);
    partial void OnrowChanged();
    #endregion
		
		public TTotal_Reading()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slot_id", DbType="VarChar(100)")]
		public string slot_id
		{
			get
			{
				return this._slot_id;
			}
			set
			{
				if ((this._slot_id != value))
				{
					this.Onslot_idChanging(value);
					this.SendPropertyChanging();
					this._slot_id = value;
					this.SendPropertyChanged("slot_id");
					this.Onslot_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier", IsPrimaryKey=true)]
		public System.Nullable<System.Guid> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChName", DbType="NChar(10)")]
		public string ChName
		{
			get
			{
				return this._ChName;
			}
			set
			{
				if ((this._ChName != value))
				{
					this.OnChNameChanging(value);
					this.SendPropertyChanging();
					this._ChName = value;
					this.SendPropertyChanged("ChName");
					this.OnChNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtime
		{
			get
			{
				return this._dtime;
			}
			set
			{
				if ((this._dtime != value))
				{
					this.OndtimeChanging(value);
					this.SendPropertyChanging();
					this._dtime = value;
					this.SendPropertyChanged("dtime");
					this.OndtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading", DbType="Float")]
		public System.Nullable<double> reading
		{
			get
			{
				return this._reading;
			}
			set
			{
				if ((this._reading != value))
				{
					this.OnreadingChanging(value);
					this.SendPropertyChanging();
					this._reading = value;
					this.SendPropertyChanged("reading");
					this.OnreadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading_units", DbType="NChar(10)")]
		public string reading_units
		{
			get
			{
				return this._reading_units;
			}
			set
			{
				if ((this._reading_units != value))
				{
					this.Onreading_unitsChanging(value);
					this.SendPropertyChanging();
					this._reading_units = value;
					this.SendPropertyChanged("reading_units");
					this.Onreading_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow", DbType="Float")]
		public System.Nullable<double> flow
		{
			get
			{
				return this._flow;
			}
			set
			{
				if ((this._flow != value))
				{
					this.OnflowChanging(value);
					this.SendPropertyChanging();
					this._flow = value;
					this.SendPropertyChanged("flow");
					this.OnflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_units", DbType="NChar(10)")]
		public string flow_units
		{
			get
			{
				return this._flow_units;
			}
			set
			{
				if ((this._flow_units != value))
				{
					this.Onflow_unitsChanging(value);
					this.SendPropertyChanging();
					this._flow_units = value;
					this.SendPropertyChanged("flow_units");
					this.Onflow_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> file_id
		{
			get
			{
				return this._file_id;
			}
			set
			{
				if ((this._file_id != value))
				{
					this.Onfile_idChanging(value);
					this.SendPropertyChanging();
					this._file_id = value;
					this.SendPropertyChanged("file_id");
					this.Onfile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_row", DbType="Int")]
		public System.Nullable<int> row
		{
			get
			{
				return this._row;
			}
			set
			{
				if ((this._row != value))
				{
					this.OnrowChanging(value);
					this.SendPropertyChanging();
					this._row = value;
					this.SendPropertyChanged("row");
					this.OnrowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Files")]
	public partial class File : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _FileName;
		
		private System.Nullable<System.DateTime> _processdate;
		
		private string _md5;
		
		private System.Nullable<System.DateTime> _date_from;
		
		private System.Nullable<System.DateTime> _date_to;
		
		private System.Nullable<int> _data_rows;
		
		private System.Nullable<bool> _invalid_data;
		
		private string _DirectoryName;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _LastWriteTimeUtc;
		
		private System.Nullable<System.DateTime> _CreationTimeUtc;
		
		private System.Nullable<long> _Length;
		
		private System.Nullable<bool> _NeedsProcessing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnprocessdateChanging(System.Nullable<System.DateTime> value);
    partial void OnprocessdateChanged();
    partial void Onmd5Changing(string value);
    partial void Onmd5Changed();
    partial void Ondate_fromChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_fromChanged();
    partial void Ondate_toChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_toChanged();
    partial void Ondata_rowsChanging(System.Nullable<int> value);
    partial void Ondata_rowsChanged();
    partial void Oninvalid_dataChanging(System.Nullable<bool> value);
    partial void Oninvalid_dataChanged();
    partial void OnDirectoryNameChanging(string value);
    partial void OnDirectoryNameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLastWriteTimeUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnLastWriteTimeUtcChanged();
    partial void OnCreationTimeUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnCreationTimeUtcChanged();
    partial void OnLengthChanging(System.Nullable<long> value);
    partial void OnLengthChanged();
    partial void OnNeedsProcessingChanging(System.Nullable<bool> value);
    partial void OnNeedsProcessingChanged();
    #endregion
		
		public File()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_processdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> processdate
		{
			get
			{
				return this._processdate;
			}
			set
			{
				if ((this._processdate != value))
				{
					this.OnprocessdateChanging(value);
					this.SendPropertyChanging();
					this._processdate = value;
					this.SendPropertyChanged("processdate");
					this.OnprocessdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_md5", DbType="VarChar(50)")]
		public string md5
		{
			get
			{
				return this._md5;
			}
			set
			{
				if ((this._md5 != value))
				{
					this.Onmd5Changing(value);
					this.SendPropertyChanging();
					this._md5 = value;
					this.SendPropertyChanged("md5");
					this.Onmd5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_from", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_from
		{
			get
			{
				return this._date_from;
			}
			set
			{
				if ((this._date_from != value))
				{
					this.Ondate_fromChanging(value);
					this.SendPropertyChanging();
					this._date_from = value;
					this.SendPropertyChanged("date_from");
					this.Ondate_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_to", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_to
		{
			get
			{
				return this._date_to;
			}
			set
			{
				if ((this._date_to != value))
				{
					this.Ondate_toChanging(value);
					this.SendPropertyChanging();
					this._date_to = value;
					this.SendPropertyChanged("date_to");
					this.Ondate_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_rows", DbType="Int")]
		public System.Nullable<int> data_rows
		{
			get
			{
				return this._data_rows;
			}
			set
			{
				if ((this._data_rows != value))
				{
					this.Ondata_rowsChanging(value);
					this.SendPropertyChanging();
					this._data_rows = value;
					this.SendPropertyChanged("data_rows");
					this.Ondata_rowsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invalid_data", DbType="Bit")]
		public System.Nullable<bool> invalid_data
		{
			get
			{
				return this._invalid_data;
			}
			set
			{
				if ((this._invalid_data != value))
				{
					this.Oninvalid_dataChanging(value);
					this.SendPropertyChanging();
					this._invalid_data = value;
					this.SendPropertyChanged("invalid_data");
					this.Oninvalid_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectoryName", DbType="VarChar(512)")]
		public string DirectoryName
		{
			get
			{
				return this._DirectoryName;
			}
			set
			{
				if ((this._DirectoryName != value))
				{
					this.OnDirectoryNameChanging(value);
					this.SendPropertyChanging();
					this._DirectoryName = value;
					this.SendPropertyChanged("DirectoryName");
					this.OnDirectoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(512)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastWriteTimeUtc", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastWriteTimeUtc
		{
			get
			{
				return this._LastWriteTimeUtc;
			}
			set
			{
				if ((this._LastWriteTimeUtc != value))
				{
					this.OnLastWriteTimeUtcChanging(value);
					this.SendPropertyChanging();
					this._LastWriteTimeUtc = value;
					this.SendPropertyChanged("LastWriteTimeUtc");
					this.OnLastWriteTimeUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationTimeUtc", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreationTimeUtc
		{
			get
			{
				return this._CreationTimeUtc;
			}
			set
			{
				if ((this._CreationTimeUtc != value))
				{
					this.OnCreationTimeUtcChanging(value);
					this.SendPropertyChanging();
					this._CreationTimeUtc = value;
					this.SendPropertyChanged("CreationTimeUtc");
					this.OnCreationTimeUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="BigInt")]
		public System.Nullable<long> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedsProcessing", DbType="Bit")]
		public System.Nullable<bool> NeedsProcessing
		{
			get
			{
				return this._NeedsProcessing;
			}
			set
			{
				if ((this._NeedsProcessing != value))
				{
					this.OnNeedsProcessingChanging(value);
					this.SendPropertyChanging();
					this._NeedsProcessing = value;
					this.SendPropertyChanged("NeedsProcessing");
					this.OnNeedsProcessingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_Total_Readings_60days")]
	public partial class v_Total_Readings_60day
	{
		
		private string _Region;
		
		private string _SiteName;
		
		private string _ChName;
		
		private System.Nullable<System.DateTime> _dtime;
		
		private System.Nullable<double> _reading;
		
		public v_Total_Readings_60day()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NChar(10)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this._SiteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChName", DbType="NChar(10)")]
		public string ChName
		{
			get
			{
				return this._ChName;
			}
			set
			{
				if ((this._ChName != value))
				{
					this._ChName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtime
		{
			get
			{
				return this._dtime;
			}
			set
			{
				if ((this._dtime != value))
				{
					this._dtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reading", DbType="Float")]
		public System.Nullable<double> reading
		{
			get
			{
				return this._reading;
			}
			set
			{
				if ((this._reading != value))
				{
					this._reading = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteStatus")]
	public partial class SiteStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SiteName;
		
		private string _CurrentUpdate;
		
		private string _LastUpdate;
		
		private System.Nullable<System.DateTime> _CurrentTimeStamp;
		
		private System.Nullable<System.DateTime> _LastTimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnCurrentUpdateChanging(string value);
    partial void OnCurrentUpdateChanged();
    partial void OnLastUpdateChanging(string value);
    partial void OnLastUpdateChanged();
    partial void OnCurrentTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentTimeStampChanged();
    partial void OnLastTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnLastTimeStampChanged();
    #endregion
		
		public SiteStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentUpdate", DbType="VarChar(254)")]
		public string CurrentUpdate
		{
			get
			{
				return this._CurrentUpdate;
			}
			set
			{
				if ((this._CurrentUpdate != value))
				{
					this.OnCurrentUpdateChanging(value);
					this.SendPropertyChanging();
					this._CurrentUpdate = value;
					this.SendPropertyChanged("CurrentUpdate");
					this.OnCurrentUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="VarChar(254)")]
		public string LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentTimeStamp
		{
			get
			{
				return this._CurrentTimeStamp;
			}
			set
			{
				if ((this._CurrentTimeStamp != value))
				{
					this.OnCurrentTimeStampChanging(value);
					this.SendPropertyChanging();
					this._CurrentTimeStamp = value;
					this.SendPropertyChanged("CurrentTimeStamp");
					this.OnCurrentTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastTimeStamp
		{
			get
			{
				return this._LastTimeStamp;
			}
			set
			{
				if ((this._LastTimeStamp != value))
				{
					this.OnLastTimeStampChanging(value);
					this.SendPropertyChanging();
					this._LastTimeStamp = value;
					this.SendPropertyChanged("LastTimeStamp");
					this.OnLastTimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteRegions")]
	public partial class SiteRegion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _id;
		
		private string _SiteName;
		
		private string _Region;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Guid value);
    partial void OnidChanged();
    partial void OnSiteNameChanging(string value);
    partial void OnSiteNameChanged();
    partial void OnRegionChanging(string value);
    partial void OnRegionChanged();
    #endregion
		
		public SiteRegion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteName", DbType="NChar(10)")]
		public string SiteName
		{
			get
			{
				return this._SiteName;
			}
			set
			{
				if ((this._SiteName != value))
				{
					this.OnSiteNameChanging(value);
					this.SendPropertyChanging();
					this._SiteName = value;
					this.SendPropertyChanged("SiteName");
					this.OnSiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NChar(10)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this.OnRegionChanging(value);
					this.SendPropertyChanging();
					this._Region = value;
					this.SendPropertyChanged("Region");
					this.OnRegionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Status")]
	public partial class Status
	{
		
		private System.Nullable<System.Guid> _id;
		
		private System.Nullable<int> _state;
		
		private string _Name;
		
		private string _Description;
		
		private string _Computer;
		
		private System.Nullable<System.DateTime> _tstamp;
		
		public Status()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Computer", DbType="VarChar(50)")]
		public string Computer
		{
			get
			{
				return this._Computer;
			}
			set
			{
				if ((this._Computer != value))
				{
					this._Computer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tstamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> tstamp
		{
			get
			{
				return this._tstamp;
			}
			set
			{
				if ((this._tstamp != value))
				{
					this._tstamp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
